//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.15 at 11:45:52 AM EDT 
//


package com.sb.loantearms;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Eligibility" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="MaxLoanAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="MonthlyPayment" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eligibility",
    "maxLoanAmount",
    "monthlyPayment"
})
@XmlRootElement(name = "LoanResponse")
public class LoanResponse {

    @XmlElement(name = "Eligibility")
    protected boolean eligibility;
    @XmlElement(name = "MaxLoanAmount", required = true)
    protected BigDecimal maxLoanAmount;
    @XmlElement(name = "MonthlyPayment", required = true)
    protected BigDecimal monthlyPayment;

    /**
     * Gets the value of the eligibility property.
     * 
     */
    public boolean isEligibility() {
        return eligibility;
    }

    /**
     * Sets the value of the eligibility property.
     * 
     */
    public void setEligibility(boolean value) {
        this.eligibility = value;
    }

    /**
     * Gets the value of the maxLoanAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxLoanAmount() {
        return maxLoanAmount;
    }

    /**
     * Sets the value of the maxLoanAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxLoanAmount(BigDecimal value) {
        this.maxLoanAmount = value;
    }

    /**
     * Gets the value of the monthlyPayment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMonthlyPayment() {
        return monthlyPayment;
    }

    /**
     * Sets the value of the monthlyPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMonthlyPayment(BigDecimal value) {
        this.monthlyPayment = value;
    }

}
